* TODO Crossing out the super list-item makes the sub list-items ilegible

Given this list item with sub-goals:

#+BEGIN_QUOTE
- Hit the gym
  - Hit the treadmill
  - Hit the squat rack
#+END_QUOTE

Crossing out the top item (“Hit the gym”) makes sub-goals ilegible.

* TODO Close buttons are not aligned in nested lists

* DONE Use a dialog prompt for inputing sublist item text
  CLOSED: [2019-10-12 Sat 17:39]

  - CLOSING NOTE [2019-10-12 Sat 17:39] \\
    See: r#a0868fb663fe (“Prompt user for input”, 2019-10-12).
Use a popup window (similar to ~alert~) to input the texts for the
subitems.  That way I don’t need to stick an input field into (or under)
the top-level list items.

* TODO The nested ~<ul></ul>~ might not be necessary

It might not be necessary to put the ~<ul></ul>~ inside each top-level
list item.

I inspected the source of the todo web app:

#+BEGIN_SRC
Meet George <ul></ul><span class="close">×</span><span
class="addsub">+</span><li class="">new item<span
class="close">×</span></li><li>new item<span
class="close">×</span></li><li>new item<span
class="close">×</span></li><li>new item<span class="close">×</span></li>
#+END_SRC

Notice that the second-level ~<li>~ tags are inside the the top-level
~<li>~ tags, not inside the ~<ul>~ tag.

* References

** ~ul~ tag (unordered list)

https://www.w3schools.com/tags/tag_ul.asp
